import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/02_Organisms/About/About'
import Customers from '../components/02_Organisms/Customers/Customers'
import Footer from '../components/02_Organisms/Footer.tsx/Footer'
import HeroTeaser from '../components/02_Organisms/HeroTeaser/HeroTeaser'
import Loader from '../components/02_Organisms/Loader/Loader'
import Projects from '../components/02_Organisms/Projects/Projects'
import WhatIDo from '../components/02_Organisms/WhatIDo/WhatIDo'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>VogelVlug Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      Hier Impressum einfügen
    </>
  )
}

export default Home
